# Generated by Django 5.2.5 on 2025-08-12 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RenameField(
            model_name='calendarevent',
            old_name='is_completed',
            new_name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='linked_debt_payment',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='linked_expense',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='linked_income',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='recurrence',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='recurrence_pattern',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='reminder_days_before',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('general', 'General'), ('bill', 'Bill Payment'), ('payday', 'Payday'), ('investment', 'Investment'), ('transfer', 'Transfer'), ('celebration', 'Celebration'), ('reminder', 'Reminder')], default='general', max_length=20),
        ),
        migrations.CreateModel(
            name='EventReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reminders', to='calendar_app.calendarevent')),
            ],
            options={
                'unique_together': {('event', 'reminder_date')},
            },
        ),
    ]
