# Generated by Django 5.2.5 on 2025-08-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_active', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='projectexpense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
