# Generated by Django 5.2.5 on 2025-08-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_options_project_parent_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-is_active', '-created_at']},
        ),
    ]
