# Generated by Django 5.2.5 on 2025-08-12 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_wire', 'Bank Wire'), ('internal', 'Internal Transfer')], max_length=20)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('amount_sent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_sent', models.CharField(choices=[('USD', 'USD'), ('KES', 'KES')], max_length=3)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency_received', models.CharField(choices=[('USD', 'USD'), ('KES', 'KES')], max_length=3)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('reason', models.TextField()),
                ('transfer_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_account_kenya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='accounts.kenyaaccount')),
                ('recipient_account_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to='accounts.usaccount')),
                ('sender_account_kenya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='accounts.kenyaaccount')),
                ('sender_account_us', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_transfers', to='accounts.usaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
