# Generated by Django 5.2.5 on 2025-08-12 06:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('money_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moneytransfer',
            options={'ordering': ['-scheduled_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='moneytransfer',
            old_name='amount_received',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='amount_sent',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='currency_received',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='currency_sent',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='recipient_account_kenya',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='recipient_account_us',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='recipient_phone',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='sender_account_kenya',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='sender_account_us',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='transfer_date',
        ),
        migrations.RemoveField(
            model_name='moneytransfer',
            name='transfer_method',
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='from_kenya_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='accounts.kenyaaccount'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='from_us_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_from', to='accounts.usaccount'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='scheduled_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='to_kenya_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='accounts.kenyaaccount'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='to_us_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_to', to='accounts.usaccount'),
        ),
        migrations.AddField(
            model_name='moneytransfer',
            name='transfer_type',
            field=models.CharField(choices=[('internal', 'Internal Transfer'), ('external', 'External Transfer')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='moneytransfer',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, default=1.0, max_digits=10),
        ),
    ]
