# Generated by Django 5.2.5 on 2025-08-12 08:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing budget', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('alert_threshold', models.IntegerField(default=80, help_text='Alert when spending reaches this percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_active', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_date', models.DateTimeField(auto_now_add=True)),
                ('percentage_reached', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='categories.budget')),
            ],
            options={
                'ordering': ['-alert_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('expense', 'Expense'), ('income', 'Income'), ('both', 'Both')], default='expense', max_length=10)),
                ('icon', models.CharField(blank=True, help_text='Icon name from Material-UI', max_length=50)),
                ('color', models.CharField(default='#2196F3', help_text='Hex color code', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
                'unique_together': {('user', 'name', 'category_type')},
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Leave blank for overall budget', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='categories.category'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'period', 'start_date')},
        ),
    ]
