# Generated by Django 5.2.5 on 2025-08-12 06:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debt',
            options={'ordering': ['-current_balance', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='debtpayment',
            options={'ordering': ['-payment_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='debtpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='debt',
            name='debt_type',
            field=models.CharField(choices=[('loan', 'Personal Loan'), ('credit_card', 'Credit Card'), ('mortgage', 'Mortgage'), ('auto', 'Auto Loan'), ('student', 'Student Loan'), ('other', 'Other')], default='loan', max_length=20),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='interest_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='principal_payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
