# Generated by Django 5.2.5 on 2025-08-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'ordering': ['deadline', '-created_at']},
        ),
        migrations.AlterField(
            model_name='goal',
            name='goal_type',
            field=models.CharField(choices=[('savings', 'Savings'), ('investment', 'Investment'), ('purchase', 'Purchase'), ('emergency', 'Emergency Fund'), ('other', 'Other')], default='savings', max_length=20),
        ),
    ]
