# Generated by Django 5.2.5 on 2025-08-12 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('expense', '0003_alter_expense_category_remove_expense_budget_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='categories.category'),
        ),
    ]
